### ISSUE TITLE
没有独显可以使用吗？

### ISSUE THREAD

**Issue by chenmishan** [superleeyom/B365ITX-Hackintosh-OpenCore#1]
您好，我的使用是华擎B365ITX-AC，cpu是i5-9400，没有使用独显和蓝牙，config.plist要修改哪些配置呢？我直接使用你的EFI文件无法正确引导

**Comment by superleeyom** [comment]
你好，我目前这台机器暂时没有在使用，是有独显版本的，你可以参考这个原作者仓库：[https://github.com/Good0007/B365ITX-Hackintosh-OC](https://github.com/Good0007/B365ITX-Hackintosh-OC)，里面有个无核显的config，你可以试试 @youkiiking
